package models.card.ironclad_cards;


public enum IroncladCardEnum {
    STRIKE_CARD("STRIKE_CARD"),
    DEFEND_CARD("DEFEND_CARD"),
    ANGER_CARD("ANGER_CARD"),
    BASH_CARD("BASH_CARD"),
    BODY_SLAM_CARD("BODY_SLAM_CARD"),
    CLASH_CARD("CLASH_CARD"),
    CLEAVE_CARD("CLEAVE_CARD"),
    CLOTHESLINE_CARD("CLOTHESLINE_CARD"),
    HEADBUTT_CARD("HEADBUTT_CARD"),
    HEAVY_BLADE_CARD("HEAVY_BLADE_CARD"),
    IRON_WAVE_CARD("IRON_WAVE_CARD"),
    PERFECTED_STRIKE_CARD("PERFECTED_STRIKE_CARD"),
    POMMEL_STRIKE_CARD("POMMEL_STRIKE_CARD"),
    SWORD_BOOMERANG_CARD("SWORD_BOOMERANG_CARD"),
    THUNDERCLAP_CARD("THUNDERCLAP_CARD"),
    TWIN_STRIKE_CARD("TWIN_STRIKE_CARD"),
    WILD_STRIKE_CARD("WILD_STRIKE_CARD"),
    BLUDGEON_CARD("BLUDGEON_CARD"),
    FEED_CARD("FEED_CARD"),
    FIEND_FIRE_CARD("FIEND_FIRE_CARD"),
    IMMOLATE_CARD("IMMOLATE_CARD"),
    REAPER_CARD("REAPER_CARD"),
    BLOOD_FOR_BLOOD_CARD("BLOOD_FOR_BLOOD_CARD"),
    CARNAGE_CARD("CARNAGE_CARD"),
    DROPKICK_CARD("DROPKICK_CARD"),
    HEMOKINESIS_CARD("HEMOKINESIS_CARD"),
    PUMMEL_CARD("PUMMEL_CARD"),
    RAMPAGE_CARD("RAMPAGE_CARD"),
    RECKLESS_CHARGE_CARD("RECKLESS_CHARGE_CARD"),
    SEARING_BLOW_CARD("SEARING_BLOW_CARD"),
    SEVER_SOUL_CARD("SEVER_SOUL_CARD"),
    UPPERCUT_CARD("UPPERCUT_CARD"),
    WHIRLWIND_CARD("WHIRLWIND_CARD"),
    BERSERK_CARD("BERSERK_CARD"),
    JUGGERNAUT_CARD("JUGGERNAUT_CARD"),
    INFLAME_CARD("INFLAME_CARD"),
    METALLICIZE_CARD("METALLICIZE_CARD"),
    RUPTURE_CARD("RUPTURE_CARD"),
    FLEX_CARD("FLEX_CARD"),
    SHRUG_IT_OFF_CARD("SHRUG_IT_OFF_CARD"),
    WARCRY_CARD("WARCRY_CARD"),
    OFFERING_CARD("OFFERING_CARD"),
    ENTRENCH_CARD("ENTRENCH_CARD"),
    GHOSTLY_ARMOR_CARD("GHOSTLY_ARMOR_CARD"),
    RAGE_CARD("RAGE_CARD"),
    SPOT_WEAKNESS_CARD("SPOT_WEAKNESS_CARD");

    private String name;

    IroncladCardEnum(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }
}
