package models.card.ironclad_cards;

public enum IroncladCards {
    IroncladStrikeCard,
    IroncladDefendCard,
    AngerCard,
    BashCard,
    BodySlamCard,
    ClashCard,
    CleaveCard,
    ClotheslineCard,
    HeadbuttCard,
    HeavyBladeCard,
    IronWaveCard,
    PerfectedStrikeCard,
    PommelStrikeCard,
    SwordBoomerangCard,
    ThunderclapCard,
    TwinStrikeCard,
    WildStrikeCard,
    BludgeonCard,
    FeedCard,
    FiendFireCard,
    ImmolateCard,
    ReaperCard,
    BloodForBloodCard,
    CarnageCard,
    DropkickCard,
    HemokinesisCard,
    PummelCard,
    RampageCard,
    RecklessChargeCard,
    SearingBlowCard,
    SeverSoulCard,
    UppercutCard,
    WhirlwindCard
}
